spring:
  application:
    name: service-discovery
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    config:
      enabled: true
      fail-fast: false

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"